### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 44587) of binary:

### ISSUE THREAD

**Issue by wbbmm** [AtlasAnalyticsLab/Vim4Path#2]
How can I fix the following error? Sincere thanks.

usage: main.py [-h] [--data_root_dir DATA_ROOT_DIR] [--max_epochs MAX_EPOCHS] [--lr LR] [--label_frac LABEL_FRAC] [--reg REG] [--seed SEED] [--k K]
               [--k_start K_START] [--k_end K_END] [--results_dir RESULTS_DIR] [--split_dir SPLIT_DIR] [--log_data] [--testing] [--early_stopping]
               [--opt {adam,sgd}] [--drop_out] [--bag_loss {svm,ce}] [--model_type {clam_sb,clam_mb,mil}] [--exp_code EXP_CODE] [--weighted_sample]
               [--model_size {small,big}] [--task {task_1_tumor_vs_normal,task_2_tumor_subtyping}] [--no_inst_cluster] [--inst_loss {svm,ce,None}] [--subtyping]
               [--bag_weight BAG_WEIGHT] [--B B]
main.py: error: unrecognized arguments: --local_rank=1 --data_path /home/projects/s4_digital_pathology-master/patch --output_dir /home/projects/mamba/Vim4Path-main/output --image_size 224 --image_size_down 96 --batch_size_per_gpu 128 --arch vim-s --disable_wand
usage: main.py [-h] [--data_root_dir DATA_ROOT_DIR] [--max_epochs MAX_EPOCHS] [--lr LR] [--label_frac LABEL_FRAC] [--reg REG] [--seed SEED] [--k K]
               [--k_start K_START] [--k_end K_END] [--results_dir RESULTS_DIR] [--split_dir SPLIT_DIR] [--log_data] [--testing] [--early_stopping]
               [--opt {adam,sgd}] [--drop_out] [--bag_loss {svm,ce}] [--model_type {clam_sb,clam_mb,mil}] [--exp_code EXP_CODE] [--weighted_sample]
               [--model_size {small,big}] [--task {task_1_tumor_vs_normal,task_2_tumor_subtyping}] [--no_inst_cluster] [--inst_loss {svm,ce,None}] [--subtyping]
               [--bag_weight BAG_WEIGHT] [--B B]
main.py: error: unrecognized arguments: --local_rank=0 --data_path /home/wjingchuan/projects/s4_digital_pathology-master/patch --output_dir /home/wjingchuan/projects/mamba/Vim4Path-main/output --image_size 224 --image_size_down 96 --batch_size_per_gpu 128 --arch vim-s --disable_wand
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 44587) of binary: /home/anaconda3/envs/bbmm/bin/python
Traceback (most recent call last):
  File "/home/anaconda3/envs/bbmm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/bbmm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/bbmm/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/anaconda3/envs/bbmm/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/wjingchuan/anaconda3/envs/bbmm/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/anaconda3/envs/bbmm/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/anaconda3/envs/bbmm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/anaconda3/envs/bbmm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/projects/mamba/Vim4Path-main/MIL/main.py FAILED

**Comment by anasiri** [comment]
Sorry for the late reply. Is this issue resolved?
